# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernard_pmf_two_stage_cpp <- function(pi, n0, n1, e1, f1, e2, k) {
    .Call('_ph2rand_bernard_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, e2, k)
}

bernard_power_one_stage <- function(pi, n0, n1, e, poss_x, poss_B) {
    .Call('_ph2rand_bernard_power_one_stage', PACKAGE = 'ph2rand', pi, n0, n1, e, poss_x, poss_B)
}

bernard_power_two_stage <- function(pi, n0, n1, e, f, poss_x, poss_B) {
    .Call('_ph2rand_bernard_power_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e, f, poss_x, poss_B)
}

bernard_terminal_two_stage_cpp <- function(n0, n1, e1, f1, e2, k) {
    .Call('_ph2rand_bernard_terminal_two_stage_cpp', PACKAGE = 'ph2rand', n0, n1, e1, f1, e2, k)
}

bernard_max_typeI <- function(J, alpha, n0, n1, e, f, poss_x, poss_B, pi_null, check) {
    .Call('_ph2rand_bernard_max_typeI', PACKAGE = 'ph2rand', J, alpha, n0, n1, e, f, poss_x, poss_B, pi_null, check)
}

bernard_min_power <- function(J, beta, delta, n0, n1, e, f, poss_x, poss_B, pi_alt, check) {
    .Call('_ph2rand_bernard_min_power', PACKAGE = 'ph2rand', J, beta, delta, n0, n1, e, f, poss_x, poss_B, pi_alt, check)
}

bernard_ess_two_stage <- function(pi, n0, n1, e1, f1) {
    .Call('_ph2rand_bernard_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1)
}

bernard_des_ess_two_stage <- function(pi, n0, n1, e1, f1, poss_x, poss_B) {
    .Call('_ph2rand_bernard_des_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, poss_x, poss_B)
}

bernard_max_ess_1d_two_stage <- function(n0, n1, e1, f1, poss_x1, poss_B1) {
    .Call('_ph2rand_bernard_max_ess_1d_two_stage', PACKAGE = 'ph2rand', n0, n1, e1, f1, poss_x1, poss_B1)
}

bernard_des_one_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_B, unique_B, point_null, pi_null, point_alt, pi_alt, summary) {
    .Call('_ph2rand_bernard_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_B, unique_B, point_null, pi_null, point_alt, pi_alt, summary)
}

bernard_des_two_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_B, unique_B, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary) {
    .Call('_ph2rand_bernard_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_B, unique_B, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary)
}

binomial_pmf_two_stage_cpp <- function(pi, n0, n1, e1, f1, e2, k) {
    .Call('_ph2rand_binomial_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, e2, k)
}

binomial_power_one_stage <- function(pi, n0, n1, e, poss_x, poss_y) {
    .Call('_ph2rand_binomial_power_one_stage', PACKAGE = 'ph2rand', pi, n0, n1, e, poss_x, poss_y)
}

binomial_power_two_stage <- function(pi, n0, n1, e, f, poss_x, poss_y) {
    .Call('_ph2rand_binomial_power_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e, f, poss_x, poss_y)
}

binomial_terminal_two_stage_cpp <- function(pi, n0, n1, e1, f1, e2, k) {
    .Call('_ph2rand_binomial_terminal_two_stage_cpp', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, e2, k)
}

binomial_max_typeI <- function(J, alpha, n0, n1, e, f, poss_x, poss_y, pi_null, check) {
    .Call('_ph2rand_binomial_max_typeI', PACKAGE = 'ph2rand', J, alpha, n0, n1, e, f, poss_x, poss_y, pi_null, check)
}

binomial_min_power <- function(J, beta, delta, n0, n1, e, f, poss_x, poss_y, pi_alt, check) {
    .Call('_ph2rand_binomial_min_power', PACKAGE = 'ph2rand', J, beta, delta, n0, n1, e, f, poss_x, poss_y, pi_alt, check)
}

binomial_ess_two_stage <- function(pi, n0, n1, e1, f1) {
    .Call('_ph2rand_binomial_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1)
}

binomial_des_ess_two_stage <- function(pi, n0, n1, e1, f1, poss_x1, poss_y1) {
    .Call('_ph2rand_binomial_des_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, poss_x1, poss_y1)
}

binomial_max_ess_1d_two_stage <- function(n0, n1, e1, f1, poss_x1, poss_y1) {
    .Call('_ph2rand_binomial_max_ess_1d_two_stage', PACKAGE = 'ph2rand', n0, n1, e1, f1, poss_x1, poss_y1)
}

binomial_des_one_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, summary) {
    .Call('_ph2rand_binomial_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, summary)
}

binomial_des_two_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary) {
    .Call('_ph2rand_binomial_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary)
}

fisher_pmf_two_stage_cpp <- function(pi, n0, n1, e1, f1, e2, k) {
    .Call('_ph2rand_fisher_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, e2, k)
}

fisher_power_one_stage <- function(pi, n0, n1, e, poss_x, poss_y, poss_z) {
    .Call('_ph2rand_fisher_power_one_stage', PACKAGE = 'ph2rand', pi, n0, n1, e, poss_x, poss_y, poss_z)
}

fisher_power_two_stage <- function(pi, n0, n1, e1, f1, e2, poss_x, poss_y, poss_z) {
    .Call('_ph2rand_fisher_power_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, e2, poss_x, poss_y, poss_z)
}

fisher_terminal_two_stage_cpp <- function(n0, n1, e1, e2, f1, k) {
    .Call('_ph2rand_fisher_terminal_two_stage_cpp', PACKAGE = 'ph2rand', n0, n1, e1, e2, f1, k)
}

fisher_max_typeI <- function(J, alpha, n0, n1, e1, f1, e2, poss_x, poss_y, poss_z, pi_null, check) {
    .Call('_ph2rand_fisher_max_typeI', PACKAGE = 'ph2rand', J, alpha, n0, n1, e1, f1, e2, poss_x, poss_y, poss_z, pi_null, check)
}

fisher_min_power <- function(J, beta, delta, n0, n1, e1, f1, e2, poss_x, poss_y, poss_z, pi_alt, check) {
    .Call('_ph2rand_fisher_min_power', PACKAGE = 'ph2rand', J, beta, delta, n0, n1, e1, f1, e2, poss_x, poss_y, poss_z, pi_alt, check)
}

fisher_ess_two_stage <- function(pi, n0, n1, e1, f1) {
    .Call('_ph2rand_fisher_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1)
}

fisher_des_ess_two_stage <- function(pi, n0, n1, e1, f1, poss_x1, poss_y1, poss_z1) {
    .Call('_ph2rand_fisher_des_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, e1, f1, poss_x1, poss_y1, poss_z1)
}

fisher_max_ess_1d_two_stage <- function(n0, n1, e1, f1, poss_x1, poss_y1, poss_z1) {
    .Call('_ph2rand_fisher_max_ess_1d_two_stage', PACKAGE = 'ph2rand', n0, n1, e1, f1, poss_x1, poss_y1, poss_z1)
}

fisher_des_one_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, summary) {
    .Call('_ph2rand_fisher_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, summary)
}

fisher_des_two_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, equal, efficacy_type, efficacy_param, futility_type, futility_param, pi_ess, summary) {
    .Call('_ph2rand_fisher_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, equal, efficacy_type, efficacy_param, futility_type, futility_param, pi_ess, summary)
}

single_double_pmf_two_stage_cpp <- function(pi, n0, n1, eS1, eT1, fS1, fT1, eS2, eT2, k) {
    .Call('_ph2rand_single_double_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, n0, n1, eS1, eT1, fS1, fT1, eS2, eT2, k)
}

single_double_power_one_stage <- function(pi, n0, n1, eS, eT, poss_x, poss_y) {
    .Call('_ph2rand_single_double_power_one_stage', PACKAGE = 'ph2rand', pi, n0, n1, eS, eT, poss_x, poss_y)
}

single_double_power_two_stage <- function(pi, n0, n1, eS, eT, fS, fT, poss_x, poss_y) {
    .Call('_ph2rand_single_double_power_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, eS, eT, fS, fT, poss_x, poss_y)
}

single_double_terminal_two_stage_cpp <- function(pi, n0, n1, eS1, eT1, fS1, fT1, eS2, eT2, k) {
    .Call('_ph2rand_single_double_terminal_two_stage_cpp', PACKAGE = 'ph2rand', pi, n0, n1, eS1, eT1, fS1, fT1, eS2, eT2, k)
}

single_double_max_typeI <- function(J, alpha, n0, n1, eS, eT, fS, fT, poss_x, poss_y, pi_null, check) {
    .Call('_ph2rand_single_double_max_typeI', PACKAGE = 'ph2rand', J, alpha, n0, n1, eS, eT, fS, fT, poss_x, poss_y, pi_null, check)
}

single_double_min_power <- function(J, beta, delta, n0, n1, eS, eT, fS, fT, poss_x, poss_y, pi_alt, check) {
    .Call('_ph2rand_single_double_min_power', PACKAGE = 'ph2rand', J, beta, delta, n0, n1, eS, eT, fS, fT, poss_x, poss_y, pi_alt, check)
}

single_double_ess_two_stage <- function(pi, n0, n1, eS1, eT1, fS1, fT1) {
    .Call('_ph2rand_single_double_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, eS1, eT1, fS1, fT1)
}

single_double_des_ess_two_stage <- function(pi, n0, n1, eS1, eT1, fS1, fT1, poss_x1, poss_y1) {
    .Call('_ph2rand_single_double_des_ess_two_stage', PACKAGE = 'ph2rand', pi, n0, n1, eS1, eT1, fS1, fT1, poss_x1, poss_y1)
}

single_double_max_ess_1d_two_stage <- function(n0, n1, eS1, eT1, fS1, fT1, poss_x1, poss_y1) {
    .Call('_ph2rand_single_double_max_ess_1d_two_stage', PACKAGE = 'ph2rand', n0, n1, eS1, eT1, fS1, fT1, poss_x1, poss_y1)
}

single_double_des_one_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, summary) {
    .Call('_ph2rand_single_double_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, summary)
}

single_double_des_two_stage_cpp <- function(alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary) {
    .Call('_ph2rand_single_double_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_n0, poss_n1, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary)
}

dbinom_des_ess <- function(dbinom1, pi_typeI, pi_power, delta, pi_ess, n0, n1) {
    .Call('_ph2rand_dbinom_des_ess', PACKAGE = 'ph2rand', dbinom1, pi_typeI, pi_power, delta, pi_ess, n0, n1)
}

dbinom_des_one_stage <- function(pi_typeI, pi_power, delta, n0, n1) {
    .Call('_ph2rand_dbinom_des_one_stage', PACKAGE = 'ph2rand', pi_typeI, pi_power, delta, n0, n1)
}

dbinom_des_two_stage <- function(dbinom1, pi_typeI, pi_power, delta, n01, n02, n11, n12) {
    .Call('_ph2rand_dbinom_des_two_stage', PACKAGE = 'ph2rand', dbinom1, pi_typeI, pi_power, delta, n01, n02, n11, n12)
}

dbinom_one_stage <- function(pi, n0, n1) {
    .Call('_ph2rand_dbinom_one_stage', PACKAGE = 'ph2rand', pi, n0, n1)
}

dbinom_two_stage <- function(pi, n0, n1) {
    .Call('_ph2rand_dbinom_two_stage', PACKAGE = 'ph2rand', pi, n0, n1)
}

pi_power_finder <- function(point_alt, pi_alt, delta) {
    .Call('_ph2rand_pi_power_finder', PACKAGE = 'ph2rand', point_alt, pi_alt, delta)
}

pi_typeI_finder <- function(point_null, pi_null) {
    .Call('_ph2rand_pi_typeI_finder', PACKAGE = 'ph2rand', point_null, pi_null)
}

