# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

barnard_pmf_two_stage_cpp <- function(pi, nC, nE, e1, f1, e2, k) {
    .Call('_ph2rand_barnard_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, e2, k)
}

barnard_power_one_stage <- function(pi, nC, nE, e, poss_x, poss_B) {
    .Call('_ph2rand_barnard_power_one_stage', PACKAGE = 'ph2rand', pi, nC, nE, e, poss_x, poss_B)
}

barnard_power_two_stage <- function(pi, nC, nE, e, f, poss_x, poss_B) {
    .Call('_ph2rand_barnard_power_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e, f, poss_x, poss_B)
}

barnard_terminal_two_stage_cpp <- function(nC, nE, e1, f1, e2, k) {
    .Call('_ph2rand_barnard_terminal_two_stage_cpp', PACKAGE = 'ph2rand', nC, nE, e1, f1, e2, k)
}

barnard_max_typeI <- function(J, alpha, nC, nE, e, f, poss_x, poss_B, Pi0, check) {
    .Call('_ph2rand_barnard_max_typeI', PACKAGE = 'ph2rand', J, alpha, nC, nE, e, f, poss_x, poss_B, Pi0, check)
}

barnard_min_power <- function(J, beta, delta, nC, nE, e, f, poss_x, poss_B, Pi1, check) {
    .Call('_ph2rand_barnard_min_power', PACKAGE = 'ph2rand', J, beta, delta, nC, nE, e, f, poss_x, poss_B, Pi1, check)
}

barnard_ess_two_stage <- function(pi, nC, nE, e1, f1) {
    .Call('_ph2rand_barnard_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1)
}

barnard_des_ess_two_stage <- function(pi, nC, nE, e1, f1, poss_x, poss_B) {
    .Call('_ph2rand_barnard_des_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, poss_x, poss_B)
}

barnard_max_ess_1d_two_stage <- function(nC, nE, e1, f1, poss_x1, poss_B1) {
    .Call('_ph2rand_barnard_max_ess_1d_two_stage', PACKAGE = 'ph2rand', nC, nE, e1, f1, poss_x1, poss_B1)
}

barnard_des_one_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_B, unique_B, point_null, Pi0, point_alt, Pi1, summary) {
    .Call('_ph2rand_barnard_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_B, unique_B, point_null, Pi0, point_alt, Pi1, summary)
}

barnard_des_two_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_B, unique_B, point_null, Pi0, point_alt, Pi1, equal, efficacy, futility, pi_ess, summary) {
    .Call('_ph2rand_barnard_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_B, unique_B, point_null, Pi0, point_alt, Pi1, equal, efficacy, futility, pi_ess, summary)
}

binomial_pmf_two_stage_cpp <- function(pi, nC, nE, e1, f1, e2, k) {
    .Call('_ph2rand_binomial_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, e2, k)
}

binomial_power_one_stage <- function(pi, nC, nE, e, poss_x, poss_y) {
    .Call('_ph2rand_binomial_power_one_stage', PACKAGE = 'ph2rand', pi, nC, nE, e, poss_x, poss_y)
}

binomial_power_two_stage <- function(pi, nC, nE, e, f, poss_x, poss_y) {
    .Call('_ph2rand_binomial_power_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e, f, poss_x, poss_y)
}

binomial_terminal_two_stage_cpp <- function(nC, nE, e1, f1, e2, k) {
    .Call('_ph2rand_binomial_terminal_two_stage_cpp', PACKAGE = 'ph2rand', nC, nE, e1, f1, e2, k)
}

binomial_max_typeI <- function(J, alpha, nC, nE, e, f, poss_x, poss_y, Pi0, check) {
    .Call('_ph2rand_binomial_max_typeI', PACKAGE = 'ph2rand', J, alpha, nC, nE, e, f, poss_x, poss_y, Pi0, check)
}

binomial_min_power <- function(J, beta, delta, nC, nE, e, f, poss_x, poss_y, pi_alt, check) {
    .Call('_ph2rand_binomial_min_power', PACKAGE = 'ph2rand', J, beta, delta, nC, nE, e, f, poss_x, poss_y, pi_alt, check)
}

binomial_ess_two_stage <- function(pi, nC, nE, e1, f1) {
    .Call('_ph2rand_binomial_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1)
}

binomial_des_ess_two_stage <- function(pi, nC, nE, e1, f1, poss_x1, poss_y1) {
    .Call('_ph2rand_binomial_des_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, poss_x1, poss_y1)
}

binomial_max_ess_1d_two_stage <- function(nC, nE, e1, f1, poss_x1, poss_y1) {
    .Call('_ph2rand_binomial_max_ess_1d_two_stage', PACKAGE = 'ph2rand', nC, nE, e1, f1, poss_x1, poss_y1)
}

binomial_des_one_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, Pi0, point_alt, pi_alt, summary) {
    .Call('_ph2rand_binomial_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, Pi0, point_alt, pi_alt, summary)
}

binomial_des_two_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, Pi0, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary) {
    .Call('_ph2rand_binomial_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, Pi0, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary)
}

fisher_pmf_two_stage_cpp <- function(pi, nC, nE, e1, f1, e2, k) {
    .Call('_ph2rand_fisher_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, e2, k)
}

fisher_power_one_stage <- function(pi, nC, nE, e, poss_x, poss_y, poss_z) {
    .Call('_ph2rand_fisher_power_one_stage', PACKAGE = 'ph2rand', pi, nC, nE, e, poss_x, poss_y, poss_z)
}

fisher_power_two_stage <- function(pi, nC, nE, e1, f1, e2, poss_x, poss_y, poss_z) {
    .Call('_ph2rand_fisher_power_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, e2, poss_x, poss_y, poss_z)
}

fisher_terminal_two_stage_cpp <- function(nC, nE, e1, e2, f1, k) {
    .Call('_ph2rand_fisher_terminal_two_stage_cpp', PACKAGE = 'ph2rand', nC, nE, e1, e2, f1, k)
}

fisher_max_typeI <- function(J, alpha, nC, nE, e1, f1, e2, poss_x, poss_y, poss_z, pi_null, check) {
    .Call('_ph2rand_fisher_max_typeI', PACKAGE = 'ph2rand', J, alpha, nC, nE, e1, f1, e2, poss_x, poss_y, poss_z, pi_null, check)
}

fisher_min_power <- function(J, beta, delta, nC, nE, e1, f1, e2, poss_x, poss_y, poss_z, pi_alt, check) {
    .Call('_ph2rand_fisher_min_power', PACKAGE = 'ph2rand', J, beta, delta, nC, nE, e1, f1, e2, poss_x, poss_y, poss_z, pi_alt, check)
}

fisher_ess_two_stage <- function(pi, nC, nE, e1, f1) {
    .Call('_ph2rand_fisher_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1)
}

fisher_des_ess_two_stage <- function(pi, nC, nE, e1, f1, poss_x1, poss_y1, poss_z1) {
    .Call('_ph2rand_fisher_des_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, e1, f1, poss_x1, poss_y1, poss_z1)
}

fisher_max_ess_1d_two_stage <- function(nC, nE, e1, f1, poss_x1, poss_y1, poss_z1) {
    .Call('_ph2rand_fisher_max_ess_1d_two_stage', PACKAGE = 'ph2rand', nC, nE, e1, f1, poss_x1, poss_y1, poss_z1)
}

fisher_des_one_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, summary) {
    .Call('_ph2rand_fisher_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, summary)
}

fisher_des_two_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, equal, efficacy_type, efficacy_param, futility_type, futility_param, pi_ess, summary) {
    .Call('_ph2rand_fisher_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, poss_z, choose_mat, point_null, pi_null, point_alt, pi_alt, equal, efficacy_type, efficacy_param, futility_type, futility_param, pi_ess, summary)
}

sat_pmf_two_stage_cpp <- function(pi, nC, nE, eS1, eT1, fS1, fT1, eS2, eT2, k) {
    .Call('_ph2rand_sat_pmf_two_stage_cpp', PACKAGE = 'ph2rand', pi, nC, nE, eS1, eT1, fS1, fT1, eS2, eT2, k)
}

sat_power_one_stage <- function(pi, nC, nE, eS, eT, poss_x, poss_y) {
    .Call('_ph2rand_sat_power_one_stage', PACKAGE = 'ph2rand', pi, nC, nE, eS, eT, poss_x, poss_y)
}

sat_power_two_stage <- function(pi, nC, nE, eS, eT, fS, fT, poss_x, poss_y) {
    .Call('_ph2rand_sat_power_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, eS, eT, fS, fT, poss_x, poss_y)
}

sat_terminal_two_stage_cpp <- function(nC, nE, eS1, eT1, fS1, fT1, eS2, eT2, k) {
    .Call('_ph2rand_sat_terminal_two_stage_cpp', PACKAGE = 'ph2rand', nC, nE, eS1, eT1, fS1, fT1, eS2, eT2, k)
}

sat_max_typeI <- function(J, alpha, nC, nE, eS, eT, fS, fT, poss_x, poss_y, pi_null, check) {
    .Call('_ph2rand_sat_max_typeI', PACKAGE = 'ph2rand', J, alpha, nC, nE, eS, eT, fS, fT, poss_x, poss_y, pi_null, check)
}

sat_min_power <- function(J, beta, delta, nC, nE, eS, eT, fS, fT, poss_x, poss_y, pi_alt, check) {
    .Call('_ph2rand_sat_min_power', PACKAGE = 'ph2rand', J, beta, delta, nC, nE, eS, eT, fS, fT, poss_x, poss_y, pi_alt, check)
}

sat_ess_two_stage <- function(pi, nC, nE, eS1, eT1, fS1, fT1) {
    .Call('_ph2rand_sat_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, eS1, eT1, fS1, fT1)
}

sat_des_ess_two_stage <- function(pi, nC, nE, eS1, eT1, fS1, fT1, poss_x1, poss_y1) {
    .Call('_ph2rand_sat_des_ess_two_stage', PACKAGE = 'ph2rand', pi, nC, nE, eS1, eT1, fS1, fT1, poss_x1, poss_y1)
}

sat_max_ess_1d_two_stage <- function(nC, nE, eS1, eT1, fS1, fT1, poss_x1, poss_y1) {
    .Call('_ph2rand_sat_max_ess_1d_two_stage', PACKAGE = 'ph2rand', nC, nE, eS1, eT1, fS1, fT1, poss_x1, poss_y1)
}

sat_des_one_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, summary) {
    .Call('_ph2rand_sat_des_one_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, summary)
}

sat_des_two_stage_cpp <- function(alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary) {
    .Call('_ph2rand_sat_des_two_stage_cpp', PACKAGE = 'ph2rand', alpha, beta, delta, poss_nC, poss_nE, poss_x, poss_y, point_null, pi_null, point_alt, pi_alt, equal, efficacy, futility, pi_ess, summary)
}

dbinom_des_ess <- function(dbinom1, pi_typeI, pi_power, delta, pi_ess, nC, nE) {
    .Call('_ph2rand_dbinom_des_ess', PACKAGE = 'ph2rand', dbinom1, pi_typeI, pi_power, delta, pi_ess, nC, nE)
}

dbinom_des_one_stage <- function(pi_typeI, pi_power, delta, nC, nE) {
    .Call('_ph2rand_dbinom_des_one_stage', PACKAGE = 'ph2rand', pi_typeI, pi_power, delta, nC, nE)
}

dbinom_des_two_stage <- function(dbinom1, pi_typeI, pi_power, delta, n1C, n2C, n1E, n2E) {
    .Call('_ph2rand_dbinom_des_two_stage', PACKAGE = 'ph2rand', dbinom1, pi_typeI, pi_power, delta, n1C, n2C, n1E, n2E)
}

dbinom_one_stage <- function(pi, nC, nE) {
    .Call('_ph2rand_dbinom_one_stage', PACKAGE = 'ph2rand', pi, nC, nE)
}

dbinom_two_stage <- function(pi, nC, nE) {
    .Call('_ph2rand_dbinom_two_stage', PACKAGE = 'ph2rand', pi, nC, nE)
}

pi_power_finder <- function(point_alt, Pi1, delta) {
    .Call('_ph2rand_pi_power_finder', PACKAGE = 'ph2rand', point_alt, Pi1, delta)
}

pi_typeI_finder <- function(point_null, Pi0) {
    .Call('_ph2rand_pi_typeI_finder', PACKAGE = 'ph2rand', point_null, Pi0)
}

